#include "cameraEvent.h"
#include "car.h"
#include "carEvent.h"
#include "collision.h"
#include "collVisitor.h"
#include "debugNode.h"
#include "DeConstructerVisitor.h"
#include "edge.h"
#include "eulerPoly.h"
#include "halfedge.h"
#include "logicRoad.h"
#include "loop.h"
#include "math.h"
#include "mulitViewer.h"
#include "Nurbs.h"
#include "pickHandler.h"
#include "plane.h"
#include "points.h"
#include "readConfig.h"
#include "recorder.h"
#include "renderVistor.h"
#include "road.h"
#include "roadSwitcher.h"
#include "solid.h"
#include "switchVisitor.h"
#include "textureVisitor.h"

#include <iostream>

#include <osgViewer/Viewer>
#include <osg/MatrixTransform>
#include <osgUtil/Optimizer>